"""empty message

Revision ID: 0d02db1788fe
Revises: 
Create Date: 2023-09-15 09:32:25.862689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d02db1788fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buddy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buddy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buddy_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_buddy_name'), ['name'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_amount'), ['amount'], unique=True)
        batch_op.create_index(batch_op.f('ix_services_service_name'), ['service_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_service_name'))
        batch_op.drop_index(batch_op.f('ix_services_amount'))

    op.drop_table('services')
    with op.batch_alter_table('buddy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buddy_name'))
        batch_op.drop_index(batch_op.f('ix_buddy_email'))

    op.drop_table('buddy')
    # ### end Alembic commands ###
